# 응용수학 방법론 HW2

In [1]:
import numpy as np

## Problem 1

In [81]:
# P : composed with eigenvectors
P = np.matrix([[1,0,0],[1,1,0],[1,1,1]]).transpose()
P

matrix([[1, 1, 1],
        [0, 1, 1],
        [0, 0, 1]])

In [82]:
P_inv = np.linalg.inv(P)
P_inv

matrix([[ 1., -1.,  0.],
        [ 0.,  1., -1.],
        [ 0.,  0.,  1.]])

In [83]:
# D : Eigenvalued Diagonal Matrix
D = np.diag([-1/3, 1/3, 1])
D

array([[-0.33333333,  0.        ,  0.        ],
       [ 0.        ,  0.33333333,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

In [84]:
A = P * D * P_inv
A

matrix([[-0.33333333,  0.66666667,  0.66666667],
        [ 0.        ,  0.33333333,  0.66666667],
        [ 0.        ,  0.        ,  1.        ]])

In [85]:
x = np.matrix([2,1,2]).transpose()
x

matrix([[2],
        [1],
        [2]])

In [55]:
# calculate directly
A**20 * x

matrix([[ 2.],
        [ 2.],
        [ 2.]])

In [49]:
# caculation by decomposition A^20 = P(D^20)P_inv
P * D**20 * P_inv * x

matrix([[ 2.],
        [ 2.],
        [ 2.]])

In [56]:
P * D**1000 * P_inv * x

matrix([[ 2.],
        [ 2.],
        [ 2.]])

## Problem 3

In [57]:
a = np.matrix([[1,0],[0,1],[-2,2]])
a

matrix([[ 1,  0],
        [ 0,  1],
        [-2,  2]])

using numpy.linalg.svd method to get U,s,V

In [58]:
U, s, V = np.linalg.svd(a, full_matrices=True)

Show the result

In [59]:
U

matrix([[ -2.35702260e-01,  -7.07106781e-01,   6.66666667e-01],
        [  2.35702260e-01,  -7.07106781e-01,  -6.66666667e-01],
        [  9.42809042e-01,  -1.11022302e-16,   3.33333333e-01]])

In [60]:
s

array([ 3.,  1.])

In [61]:
V

matrix([[-0.70710678,  0.70710678],
        [-0.70710678, -0.70710678]])

Check it is right or not <br>
diag_s : change s(vectors with singular value) to appropriate shape matrix

In [66]:
diag_s = np.diag(s)
diag_s = np.vstack([diag_s, [0,0]])
diag_s

array([[ 3.,  0.],
       [ 0.,  1.],
       [ 0.,  0.]])

In [63]:
U * diag_s * V

matrix([[  1.00000000e+00,   6.10622664e-16],
        [ -1.11022302e-16,   1.00000000e+00],
        [ -2.00000000e+00,   2.00000000e+00]])

There exists a little numerical computation error, but almost fit to a(original matrix)

## Problem 3-3

In [93]:
A = np.matrix([[1,1],[1,0],[0,1]])
A

matrix([[1, 1],
        [1, 0],
        [0, 1]])

First find SVD of A

In [94]:
U,s,V = np.linalg.svd(A, full_matrices=True)

In [95]:
pseudo_inv_A = np.linalg.inv(A.transpose() * A) * A.transpose()
pseudo_inv_A

matrix([[ 0.33333333,  0.66666667, -0.33333333],
        [ 0.33333333, -0.33333333,  0.66666667]])

Using s(singular value list), compose the pseudo inverse matrix of sigma, sigma+

In [96]:
pseudo_inv_s = np.linalg.inv(np.diag(s))
# Since it's shape should be 2 * 3, we add the empty column
pseudo_inv_s = np.column_stack((pseudo_inv_s,[0,0]))
pseudo_inv_s

array([[ 0.57735027,  0.        ,  0.        ],
       [ 0.        ,  1.        ,  0.        ]])

Check it is correct or not

In [97]:
V

matrix([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]])

In [98]:
U.transpose()

matrix([[ -8.16496581e-01,  -4.08248290e-01,  -4.08248290e-01],
        [  1.66533454e-16,  -7.07106781e-01,   7.07106781e-01],
        [ -5.77350269e-01,   5.77350269e-01,   5.77350269e-01]])

In [99]:
V * pseudo_inv_s * U.transpose()

matrix([[ 0.33333333,  0.66666667, -0.33333333],
        [ 0.33333333, -0.33333333,  0.66666667]])

In [100]:
np.linalg.inv(A.transpose()*A) * A.transpose()

matrix([[ 0.33333333,  0.66666667, -0.33333333],
        [ 0.33333333, -0.33333333,  0.66666667]])

We get the same result for A+